### PR TITLE
Regarding PR https://github.com/ElunaLuaEngine/Eluna/pull/314

### PR DESCRIPTION
**Pull request by CyberMist2**
Regarding pull request: https://github.com/ElunaLuaEngine/Eluna/pull/314

### CODE REVIEW

**Comment by Rochet2** [comment]
New hooks are not likely to be added at this time.

**Comment by imperial669** [comment]
72 failed on the check up that source is more then just a few configurations away from completing it just won't be easy to get it to work and i don't think that even Jada him self will be able to do so since i gave him that source to compile it.
Find someone to fix it for you or if you think you can do it your self go on otherwise i suggest elimination of that source

**Comment by imperial669** [comment]
don't put them before compiling
put them in the lua scripts after compiling
the eluna scripts are different type of scripts
so they don't require the core to be compiled with them
you can simply add more and more in the lua scripts folder
so make your clean build it will show a folder named build
inside you will get yout luascripts folder
there you place the scripts you want
keep in mind many of the scripts online are made for arcemu which is very
old and they might need some rework to make them work on trinity

**Comment by Niam5** [comment]
Added in 7c932967e859b50020831cc4f34f3e9e878928e2

**Pull request closed without merging**
