### PR TITLE
Add Eluna module support

### PR DESCRIPTION
**Pull request by anzz1**
To be used with PR: https://github.com/ElunaLuaEngine/Eluna/pull/412

Tested:
- [x] Windows build (MSVC 2019 v16.11.9)
- [ ] Linux build

### CODE REVIEW

**Comment by ddssxx** [comment]
linux编译显示缺失luaengine.h文件，是现在还不支持吗

**Comment by ddssxx** [comment]
Linux compilation shows that the luaengine.h file is missing. Is it not supported yet?

**Comment by Rochet2** [comment]
> Linux compilation shows that the luaengine.h file is missing. Is it not supported yet?

@ddssxx Sounds like you did not download the submodule. Did you do the step 4 of [the installation](https://github.com/ElunaLuaEngine/Eluna/blob/master/docs/INSTALL.md#installation)?

**Comment by Foereaper** [comment]
Added as of https://github.com/ElunaLuaEngine/Eluna/commit/9e32296c747197f86b5d4f5512838f75ff234d94

**Pull request closed without merging**
